# Generated by Django 3.2.5 on 2021-07-23 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management_app', '0002_remove_chefuser_continent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefuser',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chef_management_app.country'),
        ),
    ]
