# Generated by Django 3.2.5 on 2021-07-23 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management_app', '0004_alter_chefuser_country_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefuser',
            name='continent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chef_management_app.continent'),
        ),
    ]
