# Generated by Django 3.2.5 on 2021-07-23 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management_app', '0005_chefuser_continent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='continent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chef_management_app.continent'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chef_management_app.country'),
        ),
    ]
