# Generated by Django 3.2.5 on 2021-07-27 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management_app', '0006_auto_20210723_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecommentary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
