# Generated by Django 3.2.5 on 2021-07-30 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management_app', '0007_recipecommentary_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperating',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
