# Generated by Django 3.2.5 on 2021-08-12 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management_app', '0008_alter_reciperating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipesurvey',
            old_name='description',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='recipesurvey',
            name='question_eight',
        ),
        migrations.RemoveField(
            model_name='recipesurvey',
            name='question_five',
        ),
        migrations.RemoveField(
            model_name='recipesurvey',
            name='question_four',
        ),
        migrations.RemoveField(
            model_name='recipesurvey',
            name='question_nine',
        ),
        migrations.RemoveField(
            model_name='recipesurvey',
            name='question_one',
        ),
        migrations.RemoveField(
            model_name='recipesurvey',
            name='question_seven',
        ),
        migrations.RemoveField(
            model_name='recipesurvey',
            name='question_six',
        ),
        migrations.RemoveField(
            model_name='recipesurvey',
            name='question_ten',
        ),
        migrations.RemoveField(
            model_name='recipesurvey',
            name='question_three',
        ),
        migrations.RemoveField(
            model_name='recipesurvey',
            name='question_two',
        ),
        migrations.RemoveField(
            model_name='recipesurvey',
            name='recipe_id',
        ),
        migrations.RemoveField(
            model_name='recipesurvey',
            name='regularuser_id',
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.CharField(default='kdd', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RecipeRecordSurvey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=255)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.recipe')),
                ('recipesurvey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.recipesurvey')),
                ('regularuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.regularuser')),
            ],
        ),
    ]
