# Generated by Django 3.2.5 on 2021-08-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management_app', '0009_auto_20210812_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='period',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
