# Generated by Django 3.2.5 on 2021-08-14 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management_app', '0010_recipe_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularuser',
            name='continent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chef_management_app.continent'),
        ),
        migrations.AddField(
            model_name='regularuser',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chef_management_app.country'),
        ),
    ]
