# Generated by Django 3.2.5 on 2021-08-15 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management_app', '0011_auto_20210814_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularUserFavorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chefuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.chefuser')),
                ('regularuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.regularuser')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeFavorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.recipe')),
                ('regularuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.regularuser')),
            ],
        ),
    ]
