# Generated by Django 3.2.5 on 2021-08-19 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management_app', '0012_recipefavorite_regularuserfavorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='chefuser_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='message',
        ),
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.CharField(default='ff', max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='booking_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recipe_id',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.recipe'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booking_date',
            field=models.DateField(auto_now=True),
        ),
    ]
