# Generated by Django 3.2.5 on 2021-08-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management_app', '0016_auto_20210825_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='message',
            field=models.CharField(default='Payment Successful', max_length=255),
        ),
    ]
